Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCWeek9.Controllers
{
    public class AboutController: Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }

}

Controllers/AuthController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using MVCWeek9.Entities;
using MVCWeek9.Models;

namespace MVCWeek9.Controllers;

public class AuthController : Controller
{
    public static List<UserEntity> _users = new List<UserEntity>()
    {
        new UserEntity {Id=1,Email=".",Password=".",PhoneNumber=".",FullName="."} // static user list
    };

    private readonly IDataProtector _dataProtector; // for data protection , Encryption of password 

    public AuthController(IDataProtectionProvider dataProtectionProvider)
    {
        _dataProtector = dataProtectionProvider.CreateProtector("security");
    }

    [HttpGet]
    public IActionResult SignUp() // sign up get method
    {
        return View();
    }    

    [HttpPost]
    public IActionResult SignUp(AuthSignUpViewModel formData) // method of obtaining and processing information from a view  
    {
        if(!ModelState.IsValid) // ıf this is invalid data retun view 
        {
            return View(formData); // formdata go to view . If dont go data all will come data empty
        }

        var user = _users.FirstOrDefault(x => x.Email.ToLower() == formData.Email.ToLower()); // Check if there is a user

        if(user is not null) // same user
        {
            ViewBag.Error = "Kullanıcı mevcut";
            return View(formData);
        }

        var newUser = new UserEntity() // creat new user
        {
            Id = _users.Max(x=> x.Id) +1,
            Email = formData.Email.ToLower(),
            FullName = formData.FullName,
            PhoneNumber = formData.PhoneNumber,
            Password = _dataProtector.Protect(formData.Password)
        };

            _users.Add(newUser); // add user in static list

        return RedirectToAction("SignIn");
    }

    [HttpGet]
    public IActionResult SignIn() // sign in method
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignIn(AuthSignInViewModel formData)
    {

        var user = _users.FirstOrDefault(x=> x.Email.ToLower() == formData.Email.ToLower()); // check email

        if(user is null) // there is not matching user
        {
            ViewBag.Error ="Kullanıcı adı veya şifre hatalı";
            return View(formData); // go back view with data
        }

        var rawPassword = _dataProtector.Unprotect(user.Password); // decoding

        if(rawPassword == formData.Password) // check password
        {
            // Login
            
            var claims = new List<Claim>();

            claims.Add(new Claim("email",user.Email));
            claims.Add(new Claim("id",user.Id.ToString()));

            var claimIdentity = new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme);

            var autProperties = new AuthenticationProperties
            {
                AllowRefresh = true, // If you refresh the page, the account will remain open.
                ExpiresUtc = new DateTimeOffset(DateTime.Now.AddHours(48)) // for 48 hours account is login
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity),autProperties);

        }
        else // wrong password
        {
            ViewBag.Error ="Kullanıcı adı veya şifre hatalı";
            return View(formData);            
        }

        return RedirectToAction("List","Book"); // go to bookcontroller list
    }

    public async Task<IActionResult> SignOut() 
    {
        await HttpContext.SignOutAsync();

        return RedirectToAction("Index","Home"); // go to home
    }

}

Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWeek9.Entities;
using MVCWeek9.Models;

namespace MVCWeek9.Controllers;

public class AuthorController : Controller
{
    static List<AuthorEntity> _author = new List<AuthorEntity>() // static author list
    {
        new AuthorEntity{Id=1,FirstName="Fyodor",LastName="Dostoyevski",DateOfBirth=new DateTime(1821,11,11)},
        new AuthorEntity{Id=2,FirstName="Victor",LastName="Hugo",DateOfBirth=new DateTime(1802,02,26)}
    };
    public IActionResult List() // list view
    {

        var viewModel = _author.Where(x=> x.IsDeleted == false).Select(x=> new AuthorListViewModel // list all author without deleted
        {
            Id= x.Id,
            FirstName= x.FirstName,
            LastName=x.LastName,
            DateOfBirth= x.DateOfBirth
        }).ToList();


        return View(viewModel);
    }    

    [HttpGet]
    public IActionResult Creat() // new add author 
    {
        return View();
    }

    [HttpPost]
    public IActionResult Creat(AuthorCreatViewModel formData) // Adding data from the view to the list
    {
        if(!ModelState.IsValid) // go back view with data 
        {
            return View(formData);
        }

        int maxId = _author.Max(x=>x.Id); // finding max id

        var newAuthor = new AuthorEntity() // new creat author
        {
            Id= maxId+1,
            FirstName= formData.FirstName,
            LastName = formData.LastName,
            DateOfBirth = formData.DateOfBirth
        };

        _author.Add(newAuthor); // adding list


        return RedirectToAction("List");  // orientation list
    }
    
    [HttpGet]
    public IActionResult Edit(int id) // editing the author
    {
        var author = _author.Find(x=> x.Id == id); // check which author

        var viewModel = new AuthorEditViewModel() // creat viewModel and  transfer data
        {
            Id = author.Id,
            FirstName = author.FirstName,
            LastName = author.LastName,
            DateOfBirth = author.DateOfBirth
        };

        return View(viewModel); // send view model
    }


    [HttpPost]
    public IActionResult Edit(AuthorEditViewModel formData) // Adding data from the view to the list
    {

        if(!ModelState.IsValid) // go back view with data 
        {
            return View(formData);
        }

        var author = _author.Find(x=> x.Id == formData.Id); // checking list and find 

        author.FirstName = formData.FirstName; // transfer data
        author.LastName = formData.LastName; // transfer data
        author.DateOfBirth = formData.DateOfBirth; // transfer data
 

        return RedirectToAction("List"); // orientation list
    }

    
    public IActionResult Details(int id) // details view 
    {
        var author = _author.Find(x=> x.Id == id); // checking list

        var viewModel = new AuthorDetailsViewModel()  // creat view model same author data
        {
            Id= author.Id,
            FirstName =author.FirstName,
            LastName = author.LastName,
            DateOfBirth = author.DateOfBirth
        };

        return View(viewModel); // send view model
    }


    public IActionResult Delete(int id)
    {
        var author = _author.Find(x => x.Id == id); // check id and found author

        author.IsDeleted = true; // this is soft delete

        return RedirectToAction("List"); // orientation list
    }


}

Views/Shared/_FooterPartial.cshtml
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Library Managment System - <a asp-area="" ></a>
        </div>
    </footer>

Views/Shared/_Layout.cshtml
<html>
    
    <head>
        <style>
            footer{
                font-size: 18px;
                padding: 35px;
                text-align: center;
                position: absolute;
                right: 0;
                left: 0;
                bottom: 0;
            }

        </style>
        <link href="~/lib/bootstrap.css" rel="stylesheet"/>
        
        
    </head>
    <body>
        
        <partial name="_NavPartial" />
        <div class="container">

            @RenderBody()

        </div>
<div>
    <partial name="_FooterPartial" class="mt-auto"/>
</div>
        



    </body>
</html>

Views/Shared/_NavPartial.cshtml
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" asp-controller="Author" asp-action="List">Author</a>
        <a class="nav-link" asp-controller="Book" asp-action="List">Book</a>
        <a class="nav-link" asp-controller="Auth" asp-action="SignUp">Sing Up</a>
        <a class="nav-link" asp-controller="Auth" asp-action="SignIn">Sing In</a>
        <a class="nav-link" asp-controller="Auth" asp-action="SignOut">Sing Out</a>
        <a class="nav-link" asp-controller="About" asp-action="Index">About Us</a>
      </div>
    </div>
  </div>
</nav>